version: "3"
services:
    app:
        build: ./docker/app
        volumes:
            - ../:/workspace:cached
        ports:
            - 80:80
        tty: true
        environment:
            APP_ENV: local
            PHP_EXTENSION_XDEBUG: 1
            APACHE_DOCUMENT_ROOT: /workspace/public
    db:
        image: 'mysql/mysql-server:8.0'
        restart: unless-stopped
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'laravel'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'laravel'
            MYSQL_PASSWORD: 'laravel'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
