version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: 'laravel'
            DB_USERNAME: 'laravel'
            DB_PASSWORD: 'secret'
        depends_on:
            - mysql
        volumes:
            - ..:/workspace

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: 'root_password'
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'laravel'
            MYSQL_PASSWORD: 'secret'
        ports:
            - "3306:3306"

    setup-script:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DB_DATABASE: 'laravel'
            DB_USERNAME: 'laravel'
            DB_PASSWORD: 'secret'
